name: cv-nerf
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.25
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - ncurses=6.4
  - numpy=1.26.3
  - openssl=3.2.0
  - pandas=2.2.0
  - pip=23.3.2
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.4
  - python_abi=3.11
  - pytz=2023.3.post1
  - readline=8.2
  - setuptools=69.0.3
  - six=1.16.0
  - tk=8.6.13
  - tzdata=2023d
  - wheel=0.42.0
  - xz=5.2.6
  - torch=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=11.8
  - pip:
      - absl-py==2.1.0
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - einops==0.7.0
      - filelock==3.13.1
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - idna==3.6
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - kornia==0.7.1
      - markdown==3.5.2
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pillow==10.2.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - urllib3==2.1.0
      - werkzeug==3.0.1