name: cv-nerf
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.11.7
  - torch=2.1.2
  - torchvision=0.16.2
  - pip:
      - einops
      - matplotlib
      - pillow
      - tensorboard
      - tqdm
      