name: cv-nerf
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - pip
  - python=3.11.7
  - pytorch=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=11.8
  - pip:
      - einops
      - matplotlib
      - pillow
      - tensorboard
      - tqdm
      - transformers
