name: cv-nerf
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - bzip2
  - ca-certificates
  - libexpat
  - libffi
  - libsqlite
  - libzlib
  - ncurses
  - openssl
  - pip
  - python=3.11.7
  - readline
  - setuptools
  - tk
  - tzdata
  - wheel
  - xz
  - pytorch=2.12
  - pytorch-cuda=11.8
  - pip:
      - absl-py
      - cachetools
      - certifi
      - charset-normalizer
      - contourpy
      - cycler
      - filelock
      - fonttools
      - fsspec
      - google-auth
      - google-auth-oauthlib
      - grpcio
      - idna
      - jinja2
      - kiwisolver
      - markdown
      - markupsafe
      - matplotlib
      - mpmath
      - networkx
      - numpy
      - oauthlib
      - opencv-python
      - packaging
      - pillow
      - protobuf
      - pyasn1
      - pyasn1-modules
      - pyparsing
      - python-dateutil
      - requests
      - requests-oauthlib
      - rsa
      - six
      - sympy
      - tensorboard
      - tensorboard-data-server
      - typing-extensions
      - urllib3
      - werkzeug
      - kornia
      